<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Cliente_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get cliente by id_cliente
     */
    function get_cliente($id_cliente)
    {
        return $this->db->get_where('cliente',array('id_cliente'=>$id_cliente))->row_array();
    }
    
    /*
     * Get all clientes count
     */
    function get_all_clientes_count()
    {
        $this->db->from('cliente');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all clientes
     */
    function get_all_clientes($params = array())
    {
        $this->db->order_by('id_cliente', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('cliente')->result_array();
    }
        
    /*
     * function to add new cliente
     */
    function add_cliente($params)
    {
        $this->db->insert('cliente',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update cliente
     */
    function update_cliente($id_cliente,$params)
    {
        $this->db->where('id_cliente',$id_cliente);
        return $this->db->update('cliente',$params);
    }
    
    /*
     * function to delete cliente
     */
    function delete_cliente($id_cliente)
    {
        return $this->db->delete('cliente',array('id_cliente'=>$id_cliente));
    }
    
    function verificaSenha($emailCliente, $senhaCliente) {
        $this->db->where('email', $emailCliente);
        $this->db->where('senha', $senhaCliente);
        return $this->db->get('cliente')->row_array();
    }
}
