<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Itempedido extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Itempedido_model');
    } 

    /*
     * Listing of itenspedido
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('itempedido/index?');
        $config['total_rows'] = $this->Itempedido_model->get_all_itenspedido_count();
        $this->pagination->initialize($config);

        $data['itenspedido'] = $this->Itempedido_model->get_all_itenspedido($params);
        
        $data['_view'] = 'itempedido/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new itempedido
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('valor','Valor','required|numeric');
		$this->form_validation->set_rules('quantidade','Quantidade','required|integer');
		$this->form_validation->set_rules('observacoes','Observacoes','max_length[255]');
		$this->form_validation->set_rules('id_pedido','Id Pedido','required|integer');
		$this->form_validation->set_rules('id_produto','Id Produto','required|integer');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'id_produto' => $this->input->post('id_produto'),
				'valor' => $this->input->post('valor'),
				'quantidade' => $this->input->post('quantidade'),
				'observacoes' => $this->input->post('observacoes'),
				'id_pedido' => $this->input->post('id_pedido'),
            );
            
            $itempedido_id = $this->Itempedido_model->add_itempedido($params);
            redirect('itempedido/index');
        }
        else
        {
			$this->load->model('Produto_model');
			$data['all_produtos'] = $this->Produto_model->get_all_produtos();
            
            $data['_view'] = 'itempedido/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a itempedido
     */
    function edit($id_item)
    {   
        // check if the itempedido exists before trying to edit it
        $data['itempedido'] = $this->Itempedido_model->get_itempedido($id_item);
        
        if(isset($data['itempedido']['id_item']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('valor','Valor','required|numeric');
			$this->form_validation->set_rules('quantidade','Quantidade','required|integer');
			$this->form_validation->set_rules('observacoes','Observacoes','max_length[255]');
			$this->form_validation->set_rules('id_pedido','Id Pedido','required|integer');
			$this->form_validation->set_rules('id_produto','Id Produto','required|integer');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'id_produto' => $this->input->post('id_produto'),
					'valor' => $this->input->post('valor'),
					'quantidade' => $this->input->post('quantidade'),
					'observacoes' => $this->input->post('observacoes'),
					'id_pedido' => $this->input->post('id_pedido'),
                );

                $this->Itempedido_model->update_itempedido($id_item,$params);            
                redirect('itempedido/index');
            }
            else
            {
				$this->load->model('Produto_model');
				$data['all_produtos'] = $this->Produto_model->get_all_produtos();

                $data['_view'] = 'itempedido/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The itempedido you are trying to edit does not exist.');
    } 

    /*
     * Deleting itempedido
     */
    function remove($id_item)
    {
        $itempedido = $this->Itempedido_model->get_itempedido($id_item);

        // check if the itempedido exists before trying to delete it
        if(isset($itempedido['id_item']))
        {
            $this->Itempedido_model->delete_itempedido($id_item);
            redirect('itempedido/index');
        }
        else
            show_error('The itempedido you are trying to delete does not exist.');
    }
    
}
